### ISSUE TITLE
Failed to recreate stream if stream is deleted manually

### ISSUE THREAD

**Issue by zhaoyao91** [fluent-plugins-nursery/fluent-plugin-cloudwatch-logs#90] opened 2017-11-24 05:28 UTC
when `auto_create_stream` is specified, it will create the stream for the first time. but if I delete that stream from cloudwatch manually, then fluentd cannot recreate the stream an throw error.

**Comment by cosmo0920** [comment] 2020-07-10 10:31
I couldn't reproduce this issue with this configuration on fluent-plugin-cloudwatch-logs v0.10.0:

```aconf
<source>
  @type forward
</source>
<filter **>
 @type stdout
</filter>
<match cloudwatch.**>
  @type cloudwatch_logs
  region ap-northeast-1
  aws_key_id <obfuscated>
  aws_sec_key <obfuscated>
  auto_create_stream true
  log_group_name fluentd
  auto_create_stream true
  log_stream_name cloudwatchlogs_test_restrict
  message_keys message
  <buffer tag>
    @type memory
    flush_interval 2s
  </buffer>
</match>
```

```
echo '{"elmo":"3years old", "abby":"a fairy","message":"ｲｪ━━━━━ヽ( ﾟДﾟ)人(ﾟДﾟ )ﾉ━━━━━━ｲ!!🤝 from fluentd!!!!"}' | bundle exec fluent-cat cloudwatch.test       
```

Create manually deleted stream is created:
```
2020-07-10 19:29:44 +0900 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="fluent.trace"
2020-07-10 19:29:44 +0900 [debug]: #0 fluent/log.rb:302:debug: [Aws::CloudWatchLogs::Client 200 0.095126 0 retries] describe_log_groups(log_group_name_prefix:"fluentd")  

2020-07-10 19:29:44.523196000 +0900 fluent.debug: {"message":"[Aws::CloudWatchLogs::Client 200 0.095126 0 retries] describe_log_groups(log_group_name_prefix:\"fluentd\")  \n"}
2020-07-10 19:29:44 +0900 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="fluent.debug"
2020-07-10 19:29:44 +0900 [debug]: #0 fluent/log.rb:302:debug: [Aws::CloudWatchLogs::Client 200 0.027353 0 retries] describe_log_streams(log_group_name:"fluentd",log_stream_name_prefix:"cloudwatchlogs_test_restrict")  

2020-07-10 19:29:44.552435000 +0900 fluent.debug: {"message":"[Aws::CloudWatchLogs::Client 200 0.027353 0 retries] describe_log_streams(log_group_name:\"fluentd\",log_stream_name_prefix:\"cloudwatchlogs_test_restrict\")  \n"}
2020-07-10 19:29:44 +0900 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="fluent.debug"
2020-07-10 19:29:44 +0900 [debug]: #0 fluent/log.rb:302:debug: [Aws::CloudWatchLogs::Client 200 0.041372 0 retries] create_log_stream(log_group_name:"fluentd",log_stream_name:"cloudwatchlogs_test_restrict")  

2020-07-10 19:29:44.695179000 +0900 fluent.debug: {"message":"[Aws::CloudWatchLogs::Client 200 0.041372 0 retries] create_log_stream(log_group_name:\"fluentd\",log_stream_name:\"cloudwatchlogs_test_restrict\")  \n"}
2020-07-10 19:29:44 +0900 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="fluent.debug"
2020-07-10 19:29:44 +0900 [debug]: #0 fluent/log.rb:302:debug: [Aws::CloudWatchLogs::Client 200 0.042264 0 retries] put_log_events(log_events:[{timestamp:1594376981546,message:"[FILTERED]"}],log_group_name:"fluentd",log_stream_name:"cloudwatchlogs_test_restrict")  

2020-07-10 19:29:44.738840000 +0900 fluent.debug: {"message":"[Aws::CloudWatchLogs::Client 200 0.042264 0 retries] put_log_events(log_events:[{timestamp:1594376981546,message:\"[FILTERED]\"}],log_group_name:\"fluentd\",log_stream_name:\"cloudwatchlogs_test_restrict\")  \n"}
2020-07-10 19:29:44 +0900 [debug]: #0 fluent/log.rb:302:debug: Called PutLogEvents API group="fluentd" stream="cloudwatchlogs_test_restrict" events_count=1 events_bytesize=122 sequence_token=nil thread=70179871599640 request_sec=0.043185
2020-07-10 19:29:44 +0900 [trace]: #0 fluent/log.rb:281:trace: no patterns matched tag="fluent.debug"
```

Used gems:

```
% bundle exec gem list                                                                                                                                                                                                 (git)[master][OK]

*** LOCAL GEMS ***

aws-eventstream (1.0.3)
aws-partitions (1.267.0)
aws-sdk-cloudwatchlogs (1.28.0)
aws-sdk-core (3.89.1)
aws-sigv4 (1.1.0)
bundler (default: 1.17.2)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
fluent-plugin-cloudwatch-logs (0.10.0)
fluentd (1.9.0)
http_parser.rb (0.6.0)
jmespath (1.4.0)
mocha (1.11.2)
msgpack (1.3.1)
power_assert (1.1.5)
rake (13.0.1)
rr (1.2.1)
serverengine (2.2.0)
sigdump (0.2.4)
strptime (0.2.3)
test-unit (3.3.5)
test-unit-rr (1.0.5)
tzinfo (2.0.1)
tzinfo-data (1.2019.3)
yajl-ruby (1.4.1)
```

**Comment by cosmo0920** [comment] 2020-07-10 10:32
Stuck issue and incomplete information to reproduce.
Closing.

**Closed by cosmo0920** 2020-07-10 10:32 UTC
